development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: tasktickular_development
  pool: 5

test: &test
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: tasktickular_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: tasktickular_production
  pool: 5
  username: tasktickular-web
  password: